# Generated by Django 3.0.6 on 2020-08-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rickUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('shortcode', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'unique_together': {('url', 'shortcode')},
            },
        ),
    ]
