# Generated by Django 3.0.6 on 2020-08-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rickurl',
            name='url',
            field=models.CharField(max_length=600),
        ),
    ]
